name: backend
type: service
runtime: python
source:
  directory: /backend
  build_command: pip install -r requirements.txt
  run_command: python manage.py runserver
env:
  variables:
    - name: DJANGO_SETTINGS_MODULE
      value: myproject.settings
    - name: SECRET_KEY
      value: your_secret_key
    - name: DEBUG
      value: "True"
    - name: ALLOWED_HOSTS
      value: "localhost,127.0.0.1"
    - name: DATABASE_URL
      value: your_database_url
    - name: STATIC_ROOT
      value: /path/to/staticfiles
    - name: MEDIA_ROOT
      value: /path/to/mediafiles
build:
  language: python
  version: 3.9
  commands:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py migrate
deploy:
  strategy: auto
  container_port: 8000
  healthcheck:
    path: /
    interval: 30s
    timeout: 5s
    retries: 3
logging:
  level: info
  destination: logs/choreo
